Fix #8 Update api rest pattern
ckyeon/To-Do-List_2 pull request #9
Opened 2022-01-29 09:20 UTC by dsjinwongo

2022-01-29 09:30 UTC, vcho1958 requested changes

2022-01-29 09:30 UTC, vcho1958 commented on backend/routes/controller.js
>      await todolist.create({ text: req.body.text });
todolist.create(req.body);로 하시는 게 낫지 않나요?
굳이 다른 프로퍼티 안받으시는 이유가 뭔가용

2022-01-29 09:30 UTC, vcho1958 commented on backend/routes/controller.js
>      const list= await todolist.find();
준성님과 같은이유인데 todolist.find(req.query);
정도는 넣어주세요!

2022-01-29 09:30 UTC, vcho1958 commented on backend/routes/controller.js
> +    res.json(createResponse(res, ''));
res.json(createResponse(res, ''));
아까 코멘트 달았는데 메일확인 해주세여

2022-01-29 09:30 UTC, vcho1958 commented on backend/routes/controller.js
> +    await todolist.deleteOne({id});
{_id:id}하셔야죵
몽고DB는 PK가 _id컬럼이에요

2022-01-29 09:30 UTC, vcho1958 commented on backend/routes/controller.js
> +    await todolist.updateOne({id}, {done});
위 코멘트와 내용 같구요 
await todolist.updateOne({id}, body);
해주셔야해요 update하면 나머지 컬럼은 덮어씌워져서
body 넣어주세요.
아니면 {$set:{done}} 이렇게 해주셔도돼요

2022-01-30 06:21 UTC, dsjinwongo commented on backend/routes/controller.js
>      await todolist.create({ text: req.body.text });
음 몰랐어요!!ㅎ..ㅎ

2022-01-30 06:24 UTC, dsjinwongo commented on backend/routes/controller.js
>      const list= await todolist.find();
전부 찾는거라서 전달받는 쿼리문이 없는데 혹시 이경우에도 써도 상관없나요??

2022-01-30 06:35 UTC, merged

2022-01-30 06:40 UTC, vcho1958 commented on backend/routes/controller.js
>      const list= await todolist.find();
상관 없는 게 아니라 일반적으로 쓰긴 합니다
query자체가 그럴 때 사용하라고 있는거에요
나중에 검색 구현할 때 URI에 쿼리로 날아오면 그대로 데이터베이스에 검색해주는 역할 합니다.

2022-01-30 06:41 UTC, vcho1958 commented on backend/routes/controller.js
>      const list= await todolist.find();
전부 찾는거랑 일부만 찾는거랑 분리하지마시고 query를 프론트쪽에서 처리해서 백엔드에서 해당 조건을 query로 ORM에 전달하면 해당되는 목록들이 반환되는 거에요.